---
title: "Final Project"
description: |
  Exploring the relationship between GDP per capita and percentage of population with a confirmed case of COVID-19.
site: distill::distill_website
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(tidyverse)
library(primer.data)
library(lubridate)
library(dbplyr)
library(janitor)
library(skimr)
library(tibble)
library(rvest)
library(ggthemes)
library(plotly)
```


```{r, echo = FALSE}
covid <- read_rds("recent_covid.rds")
gdp <- read_rds("gdp.rds")
pop <- read_rds("pop.rds")

covid_gdp <- inner_join(covid, gdp, by = "Country")
clean_tibble <- inner_join(covid_gdp, pop, by = "Country") %>% 
  mutate(covidpc = Confirmed/Population) %>% 
  mutate(pop_perc = Population/7870000000)

``` 

```{r, echo = FALSE}
CGDP <- clean_tibble %>% 
  ggplot(aes(GDP, covidpc, color = pop_perc, 
  text = paste("Country:", Country,
    "\nGDP per Capita:", GDP,
  "\nConfirmed Cases Percentage:", covidpc, 
  "\nPopulation Percentage:", pop_perc))) +
  geom_jitter(width = 5000, height = .01, alpha = 0.7) +
  geom_smooth(method = "loess", formula = y~x, se = FALSE, color = "red2") +
  scale_color_gradient(low = "blue4", high = "cyan1", labels = scales::percent) +
  scale_y_continuous(labels = scales::percent) +
  labs(title = "Relationship Between Percentage of Population with \na Confirmed Case of COVID-19 and GDP per Capita",
       x = "GDP per Capita",
       y = "COVID-19 Percentage",
       color = "Percent of \nWorld Population",
       caption = "Sources: Datahub, Kaggle, & World Bank")
  

```

```{r, echo = FALSE}
clean_tibble %>% 
ggplot(aes(GDP, covidpc, color = pop_perc)) +
  geom_jitter(width = 5000, height = .01, alpha = 0.7) +
  geom_smooth(method = "loess", formula = y~x, se = FALSE, color = "red2") +
  scale_color_gradient(low = "blue4", high = "cyan1", labels = scales::percent) +
  scale_y_continuous(labels = scales::percent) +
  labs(title = "Relationship Between Percentage of Population with \na Confirmed Case of COVID-19 and GDP per Capita",
       x = "GDP per Capita",
       y = "COVID-19 Percentage",
       color = "Percent of \nWorld Population",
       caption = "Sources: Datahub, Kaggle, & World Bank") +
  theme_clean()
```

### Relationship between GDP per capita and percentage of population with a confirmed case of COVID-19 seems to be logarithmic. Population does not seem to have any correlation with either variable.

```{r, echo = FALSE}
ggplotly(CGDP, tooltip = "text")
```
